# ----
# Site

title: NiceGit
url: "https://nicegit.com"
google_analytics_key: G-CGP3T823NG
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: NiceGit - Source control for normal people
author:
  name: Dan
  email: dan@nicegit.com
  twitter: # twitter username without the @ symbol
social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  team:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "team"
    values:
      layout: "team_member"
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# -----------
# CloudCannon

social_icons:
  # - Facebook
  # - Google Plus
  # - Instagram
  # - LinkedIn
  # - Pinterest
  # - Tumblr
  # - Twitter
  # - YouTube
  # - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window

# --------
# Downloads

downloads:
  builds:
    - version: "0.2.0"
      mac_filename: "NiceGit-0.2.0-universal.dmg"
      date: "2025-11-07"
    - version: "0.2.1"
      mac_filename: "NiceGit-0.2.1-universal.dmg"
      date: "2025-11-11"
    - version: "0.2.2"
      mac_filename: "NiceGit-0.2.2-universal.dmg"
      date: "2025-11-14"
    - version: "0.3.2"
      mac_filename: "NiceGit-0.3.2-universal.dmg"
      date: "2025-11-28"
    - version: "0.4.1"
      mac_filename: "NiceGit-0.4.1-universal.dmg"
      date: "2025-12-05"
    - version: "0.5.1"
      mac_filename: "NiceGit-0.5.1-universal.dmg"
      windows_filename: "NiceGit-0.5.1 Setup.exe"
      date: "2025-12-16"
    - version: "0.6.0"
      mac_filename: "NiceGit-0.6.0-universal.dmg"
      windows_filename: "NiceGit-0.6.0 Setup.exe"
      date: "2026-01-27"
    - version: "0.7.0"
      mac_filename: "NiceGit-0.7.0-universal.dmg"
      windows_filename: "NiceGit-0.7.0 Setup.exe"
      date: "2026-01-27"
    - version: "0.8.1"
      mac_filename: "NiceGit-0.8.1-universal.dmg"
      windows_filename: "NiceGit-0.8.1 Setup.exe"
      date: "2026-02-11"
    - version: "0.8.2"
      mac_filename: "NiceGit-0.8.2-universal.dmg"
      windows_filename: "NiceGit-0.8.2 Setup.exe"
      date: "2026-02-12"
    - version: "0.8.3"
      mac_filename: "NiceGit-0.8.3-universal.dmg"
      windows_filename: "NiceGit-0.8.3 Setup.exe"
      date: "2026-02-13"
    - version: "0.8.4"
      mac_filename: "NiceGit-0.8.4-universal.dmg"
      windows_filename: "NiceGit-0.8.4 Setup.exe"
      date: "2026-02-17"
    - version: "0.9.0"
      mac_filename: "NiceGit-0.9.0-universal.dmg"
      windows_filename: "NiceGit-0.9.0 Setup.exe"
      date: "2026-02-25"
  current_version: "0.9.0"
